version: '3'

services:
  blockchain:
    image: trufflesuite/ganache-cli
    expose:
      - "8545"
  web:
    build: .
    command: python -m flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - blockchain