version: '3'

services:
  blockchain:
    image: trufflesuite/ganache-cli
    expose:
      - "8545"
  web:
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - blockchain